[functions.admin-generate-link]
enabled = true
verify_jwt = true
import_map = "./functions/admin-generate-link/deno.json"
entrypoint = "./functions/admin-generate-link/index.ts"

[functions.chat-support]
enabled = true
verify_jwt = false
entrypoint = "./functions/chat-support/index.ts"

[functions.analyze-contract]
enabled = true
verify_jwt = false
entrypoint = "./functions/analyze-contract/index.ts"
