[functions.admin-generate-link]
enabled = true
verify_jwt = true
import_map = "./functions/admin-generate-link/deno.json"
entrypoint = "./functions/admin-generate-link/index.ts"

[functions.chat-support]
enabled = true
verify_jwt = false
entrypoint = "./functions/chat-support/index.ts"

[functions.fetch-index-data]
enabled = true
verify_jwt = false
entrypoint = "./functions/fetch-index-data/index.ts"

[functions.analyze-contract]
enabled = true
verify_jwt = true
entrypoint = "./functions/analyze-contract/index.ts"

[functions.generate-report]
enabled = true
verify_jwt = true
entrypoint = "./functions/generate-report/index.ts"

[functions.google-maps-proxy]
enabled = true
verify_jwt = false
entrypoint = "./functions/google-maps-proxy/index.ts"

[functions.smart-function]
enabled = true
verify_jwt = false
entrypoint = "./functions/smart-function/send-contact-email.ts"

[functions.smart-processor]
enabled = true
verify_jwt = false
entrypoint = "./functions/smart-processor/fetch-index-data.ts"

[functions.hyper-worker]
enabled = true
verify_jwt = true
entrypoint = "./functions/hyper-worker/index.ts"

[functions.smooth-processor]
enabled = true
verify_jwt = true
entrypoint = "./functions/smooth-processor/index.ts"
